name: ERD Submission
description: Submit your ERD file for review (no PR needed)
title: "Submission: <Firstname Lastname>"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Attach your `.erd` file below (drag-and-drop). Ensure you have installed the BIGER Modeling Tool extension in VS Code and validated your model.

  - type: input
    id: name
    attributes:
      label: Full Name
      placeholder: Firstname Lastname
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
      placeholder: you@example.com
    validations:
      required: false

  - type: input
    id: section
    attributes:
      label: Section (if applicable)
      placeholder: e.g., Section 01
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      placeholder: Anything the instructor/TA should know
    validations:
      required: false

